FROM python:3.11-buster

ENV PYTHONUNBUFFERED=1

# create code directory
RUN mkdir /code
WORKDIR /code

# copy just requirement files and install before rest of code to avoid having to
# reinstall packages during build every time code changes
COPY ./requirements/base.txt /code/
COPY ./requirements/local.txt /code/

# upgrade pip and install requirements
RUN pip install --upgrade pip
RUN pip install -r local.txt

# copy code files
COPY . /code/

EXPOSE 8000
STOPSIGNAL SIGINT
