FROM python:3.11-buster
ENV PYTHONUNBUFFERED=1

RUN mkdir /code
WORKDIR /code

COPY ./requirements/base.txt /code/
COPY ./requirements/production.txt /code/

RUN pip install --upgrade pip
RUN pip install -r production.txt
COPY . /code/

RUN python manage.py collectstatic --noinput  --settings=gb_demo.settings.production

EXPOSE 8000
STOPSIGNAL SIGINT

RUN chmod -R +x deploy.sh
