# Generated by Django 4.2.4 on 2023-10-12 22:48

from django.db import migrations, models
import macaddress.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of this computer', max_length=250)),
                ('description', models.TextField(blank=True, help_text='Description of the computer', null=True)),
                ('mac_address', macaddress.fields.MACAddressField(help_text='Mac Address of this computer', integer=False, max_length=17)),
                ('ip_address', models.GenericIPAddressField(help_text='IP Address of this computer')),
                ('employee_abbrev', models.CharField(blank=True, help_text="Employee's name abbreviation", max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
